configs  = {  1, 'disturbance', "former",     "Step",     "A/C-ratio of stream 4, B composition constant";
              2, "disturbance", "former",     "Step",     "B composition of stream 4, A/C-ratio constant";
              3, "disturbance", "former",     "Step",     "D feed (stream 2) temperature";
              4, "disturbance", "former",     "Step",     "Cooling water inlet temperature of reactor";
              5, "disturbance", "former",     "Step",     "Cooling water inlet temperature of separator";
              6, "disturbance", "former",     "Step",     "A feed loss (stream 1)";
              7, "disturbance", "former",     "Step",     "C header pressure loss (stream 4)";
              8, "disturbance", "former",     "Random",   "A/B/C composition of stream 4";
              9, "disturbance", "former",     "Random",   "D feed (stream 2) temperature";
             10, "disturbance", "former",     "Random",   "C feed (stream 4) temperature";
             11, "disturbance", "former",     "Random",   "Cooling water inlet temperature of reactor";
             12, "disturbance", "former",     "Random",   "Cooling water inlet temperature of separator";
             13, "disturbance", "former",     "Drift",    "Reaction kinetics";
             14, "disturbance", "former",     "Stiction", "Cooling water outlet valve of reactor";
             15, "disturbance", "former",     "Stiction", "Cooling water outlet valve of separator";
             16, "disturbance", "former",     "Random",   "(unknown); deviations of heat transfer within stripper; (heat exchanger)";
             17, "disturbance", "former",     "Random",   "(unknown); deviations of heat transfer within reactor";
             18, "disturbance", "former",     "Random",   "(unknown); deviations of heat transfer within condenser";
             19, "disturbance", "former",     "Stiction", "(unknown); re-cycle valve of compressor, underflow separator (stream 10), underflow stripper (stream 11) and steam valve stripper";
             20, "disturbance", "former",     "Random",   "(unknown)";
             21, "disturbance", "additional", "Random",   "A feed (stream 1) temperature";
             22, "disturbance", "additional", "Random",   "E feed (stream 3) temperature";
             23, "disturbance", "additional", "Random",   "A feed (stream 1) pressure ( = flow)";
             24, "disturbance", "additional", "Random",   "D feed (stream 2) pressure ( = flow)";
             25, "disturbance", "additional", "Random",   "E feed (stream 3) pressure ( = flow)";
             26, "disturbance", "additional", "Random",   "A & C feed (stream 4) pressure ( = flow)";
             27, "disturbance", "additional", "Random",   "Cooling water pressure ( = flow) of reactor";
             28, "disturbance", "additional", "Random",   "Cooling water pressure ( = flow) of condenser";
             29, "failure",     "secure",     "Lock",     "1";
             30, "failure",     "secure",     "Lock",     "2";
             31, "failure",     "secure",     "Lock",     "3";
             32, "failure",     "secure",     "Lock",     "4";
             33, "failure",     "secure",     "Lock",     "5";
             34, "failure",     "secure",     "Lock",     "6";
             35, "failure",     "secure",     "Lock",     "7";
             36, "failure",     "secure",     "Lock",     "8";
             37, "failure",     "secure",     "Lock",     "9";
             38, "failure",     "secure",     "Lock",     "10";
             39, "failure",     "secure",     "Lock",     "11";
             40, "failure",     "secure",     "Lock",     "12"};
         
% save("reg_db", "configs")
% dlmwrite('configs.csv', configs);   
