dists = [ 1, "former",     "Step",     "A/C-ratio of stream 4, B composition constant";
          2, "former",     "Step",     "B composition of stream 4, A/C-ratio constant";
          3, "former",     "Step",     "D feed (stream 2) temperature";
          4, "former",     "Step",     "Cooling water inlet temperature of reactor";
          5, "former",     "Step",     "Cooling water inlet temperature of separator";
          6, "former",     "Step",     "A feed loss (stream 1)";
          7, "former",     "Step",     "C header pressure loss (stream 4)";
          8, "former",     "Random",   "A/B/C composition of stream 4";
          9, "former",     "Random",   "D feed (stream 2) temperature";
         10, "former",     "Random",   "C feed (stream 4) temperature";
         11, "former",     "Random",   "Cooling water inlet temperature of reactor";
         12, "former",     "Random",   "Cooling water inlet temperature of separator";
         13, "former",     "Drift",    "Reaction kinetics";
         14, "former",     "Stiction", "Cooling water outlet valve of reactor";
         15, "former",     "Stiction", "Cooling water outlet valve of separator";
         16, "former",     "Random",   "(unknown); deviations of heat transfer within stripper; (heat exchanger)";
         17, "former",     "Random",   "(unknown); deviations of heat transfer within reactor";
         18, "former",     "Random",   "(unknown); deviations of heat transfer within condenser";
         19, "former",     "Stiction", "(unknown); re-cycle valve of compressor, underflow separator (stream 10), underflow stripper (stream 11) and steam valve stripper";
         20, "former",     "Random",   "(unknown)";
         21, "additional", "Random",   "A feed (stream 1) temperature";
         22, "additional", "Random",   "E feed (stream 3) temperature";
         23, "additional", "Random",   "A feed (stream 1) pressure ( = flow)";
         24, "additional", "Random",   "D feed (stream 2) pressure ( = flow)";
         25, "additional", "Random",   "E feed (stream 3) pressure ( = flow)";
         26, "additional", "Random",   "A & C feed (stream 4) pressure ( = flow)";
         27, "additional", "Random",   "Cooling water pressure ( = flow) of reactor";
         28, "additional", "Random",   "Cooling water pressure ( = flow) of condenser"];