ids = [ 1; 2; 3; 4; 5;
        6; 7; 8; 9;10;
       11;12;13;14;15;
       16;17;18;19;20;
       21;22;23;24;25;
       26;27;28];
from = [    "FORMER";    "FORMER";    "FORMER";    "FORMER";    "FORMER";
            "FORMER";    "FORMER";    "FORMER";    "FORMER";    "FORMER";
            "FORMER";    "FORMER";    "FORMER";    "FORMER";    "FORMER";
            "FORMER";    "FORMER";    "FORMER";    "FORMER";    "FORMER";
        "ADDITIONAL";"ADDITIONAL";"ADDITIONAL";"ADDITIONAL";"ADDITIONAL";
        "ADDITIONAL";"ADDITIONAL";"ADDITIONAL";];
type = [  "STEP";  "STEP"; "STEP";     "STEP";    "STEP";
          "STEP";  "STEP";"RANDOM";  "RANDOM";  "RANDOM";
        "RANDOM";"RANDOM";" DRIFT";"STICTION";"STICTION";
        "RANDOM";"RANDOM";"RANDOM";"STICTION";  "RANDOM";
        "RANDOM";"RANDOM";"RANDOM";  "RANDOM";  "RANDOM";
        "RANDOM";"RANDOM";"RANDOM";];
desc = [ "A/C-ratio of stream 4, B composition constant";
         "B composition of stream 4, A/C-ratio constant";
         "D feed (stream 2) temperature";
         "Cooling water inlet temperature of reactor";
         "Cooling water inlet temperature of separator";
         "A feed loss (stream 1)";
         "C header pressure loss (stream 4)";
         "A/B/C composition of stream 4";
         "D feed (stream 2) temperature";
         "C feed (stream 4) temperature";
         "Cooling water inlet temperature of reactor";
         "Cooling water inlet temperature of separator";
         "Reaction kinetics";
         "Cooling water outlet valve of reactor";
         "Cooling water outlet valve of separator";
         "(unknown); deviations of heat transfer within stripper; (heat exchanger)";
         "(unknown); deviations of heat transfer within reactor";
         "(unknown); deviations of heat transfer within condenser";
         "(unknown); re-cycle valve of compressor, underflow separator (stream 10), underflow stripper (stream 11) and steam valve stripper";
         "(unknown)";
         "A feed (stream 1) temperature";
         "E feed (stream 3) temperature";
         "A feed (stream 1) pressure ( = flow)";
         "D feed (stream 2) pressure ( = flow)";
         "E feed (stream 3) pressure ( = flow)";
         "A & C feed (stream 4) pressure ( = flow)";
         "Cooling water pressure ( = flow) of reactor";
         "Cooling water pressure ( = flow) of condenser"];
dists = table(ids, from, type, desc, 'VariableNames', {'ID', 'FROM', 'TYPE', 'DESC'});
clearvars ids from type desc